/* eslint-disable */
// Auto-generated by scripts/generate-content-registry.ts — do not edit.
import type { ComponentType } from 'react'

export type ContentModule = {
  default: ComponentType
}

export const contentRegistryKeys = [
  'notes/component-showcase',
  'notes/purpose-of-writing',
] as const

export type ContentRegistryKey = (typeof contentRegistryKeys)[number]

export function loadContentModule(key: string): Promise<ContentModule> | null {
  switch (key) {
    case 'notes/component-showcase':
      return import('../../content/notes/component-showcase/index.mdx') as Promise<ContentModule>
    case 'notes/purpose-of-writing':
      return import('../../content/notes/purpose-of-writing/index.mdx') as Promise<ContentModule>
    default:
      return null
  }
}
