import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import matter from 'gray-matter'

import { includeDraftEntries } from '@/lib/content/draftPolicy'
import { parseContentFrontMatter } from '@/lib/content/frontmatter'
import {
  CONTENT_KINDS,
  contentEntryFile,
  contentKindDir,
  isValidContentSlug,
} from '@/lib/content/paths'
import type { ContentKind } from '@/lib/content/types'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const defaultOutFile = path.join(root, 'lib/content/registry.generated.ts')

type RegistryEntry = {
  kind: ContentKind
  slug: string
  key: string
}

function isDirectory(filePath: string): boolean {
  try {
    return fs.statSync(filePath).isDirectory()
  } catch {
    return false
  }
}

function collectEntries(): RegistryEntry[] {
  const entries: RegistryEntry[] = []
  const allowDrafts = includeDraftEntries()

  for (const kind of CONTENT_KINDS) {
    const kindDir = contentKindDir(kind)
    if (!isDirectory(kindDir)) {
      continue
    }

    for (const slug of fs.readdirSync(kindDir).sort((a, b) => a.localeCompare(b))) {
      if (!isDirectory(path.join(kindDir, slug))) {
        continue
      }
      if (!isValidContentSlug(slug)) {
        console.warn(`Skipping invalid content slug: ${kind}/${slug}`)
        continue
      }

      const indexPath = contentEntryFile(kind, slug)
      if (!fs.existsSync(indexPath)) {
        continue
      }

      const { data } = matter(fs.readFileSync(indexPath, 'utf8'))

      // Mirror load.ts: skip boolean drafts before parse when drafts are off,
      // so a WIP invalid draft cannot fail production registry generation.
      if (!allowDrafts && data.draft === true) {
        continue
      }

      let frontMatter
      try {
        frontMatter = parseContentFrontMatter(data, kind, slug)
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        // Broken drafts are never hard-fail; invalid published entries are.
        if (data.draft === true) {
          console.warn(`Skipping invalid draft ${kind}/${slug}: ${message}`)
          continue
        }
        throw new Error(`Invalid content ${kind}/${slug}: ${message}`)
      }

      if (frontMatter.draft && !allowDrafts) {
        continue
      }

      entries.push({ kind, slug, key: `${kind}/${slug}` })
    }
  }

  return entries
}

export function writeContentRegistry(
  outFile = process.env.CONTENT_REGISTRY_OUT
    ? path.resolve(process.env.CONTENT_REGISTRY_OUT)
    : defaultOutFile
): RegistryEntry[] {
  const entries = collectEntries()
  const caseLines = entries.map(
    (entry) => `    case '${entry.key}':
      return import('../../content/${entry.kind}/${entry.slug}/index.mdx') as Promise<ContentModule>`
  )

  const source = `/* eslint-disable */
// Auto-generated by scripts/generate-content-registry.ts — do not edit.
import type { ComponentType } from 'react'

export type ContentModule = {
  default: ComponentType
}

export const contentRegistryKeys = [
${entries.map((entry) => `  '${entry.key}',`).join('\n')}
] as const

export type ContentRegistryKey = (typeof contentRegistryKeys)[number]

export function loadContentModule(key: string): Promise<ContentModule> | null {
  switch (key) {
${caseLines.join('\n')}
    default:
      return null
  }
}
`

  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  fs.writeFileSync(outFile, source)
  const mode = includeDraftEntries() ? 'including drafts' : 'published only'
  console.log(
    `Wrote ${entries.length} content modules to ${path.relative(root, outFile)} (${mode})`
  )
  return entries
}

const isMain =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (isMain) {
  writeContentRegistry()
}
